export type LayoutMode = 'minimal' | 'focus' | 'dashboard';
export type SpanValue = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
export type CardType = 'bookmark' | 'clock' | 'note' | 'todo' | 'subscription' | 'tab-groups' | 'native-bookmarks';
export type CardDensity = 'comfortable' | 'compact';
export type SearchEngine = 'google' | 'bing' | 'duckduckgo' | 'brave' | 'custom';
export type ClockFormat = '12h' | '24h';
export type BackgroundType = 'solid' | 'gradient' | 'image' | 'none';
export type TodoPriority = 'high' | 'medium' | 'low' | 'none';
export type AppLanguage = 'auto' | 'en' | 'ar' | 'de';

export interface Board {
  id: string;
  name: string;
  icon: string;
  categoryIds: string[];
  createdAt: string;
  updatedAt: string;
}

export interface BookmarkCategory {
  id: string;
  boardId: string;
  name: string;
  icon: string;
  color: string;
  bookmarkIds: string[];
  collapsed: boolean;
  colSpan?: SpanValue;
  rowSpan?: SpanValue;
  cardType?: CardType;
  noteContent?: string;
  quoteIndex?: number;
  quoteChangedAt?: string;
  createdAt: string;
  /** When set, this category is a sub-folder nested inside the given parent category */
  parentCategoryId?: string;
}

export interface BookmarkEntry {
  id: string;
  categoryId: string;
  title: string;
  url: string;
  favIconUrl: string;
  addedAt: string;
  isNative: boolean;
  nativeId?: string;
  /** User-defined label / tag for this bookmark */
  category?: string;
  /** Optional free-text note about this bookmark */
  description?: string;
}

export interface QuickLink {
  id: string;
  title: string;
  url: string;
  favIconUrl: string;
  position: number;
  isAutoGenerated: boolean;
}

export interface TodoItem {
  id: string;
  listId: string;
  text: string;
  completed: boolean;
  priority: TodoPriority;
  dueDate?: string;
  position: number;
  createdAt: string;
  completedAt?: string;
}

export interface TodoList {
  id: string;
  name: string;
  icon: string;
  position: number;
  createdAt: string;
}

export interface GradientPreset {
  id: string;
  name: string;
  stops: string[];
  angle: number;
}

export type SidebarControl = 'expanded' | 'collapsed' | 'expand-on-hover';

export interface NewTabSettings {
  enabled: boolean;
  layoutMode: LayoutMode;
  cardDensity: CardDensity;
  searchEngine: SearchEngine;
  customSearchUrl?: string;
  clockFormat: ClockFormat;
  showClock: boolean;
  showQuickLinks: boolean;
  showTodo: boolean;
  showSessions: boolean;
  showBookmarks: boolean;
  backgroundType: BackgroundType;
  backgroundColor: string;
  backgroundGradientStops: string[];
  backgroundGradientAngle: number;
  backgroundImageId?: string;
  backgroundBlur: number;
  backgroundDimming: number;
  backgroundSaturation: number;
  backgroundBrightness: number;
  backgroundVignette: boolean;
  dailyRotation: boolean;
  theme: 'light' | 'dark' | 'system';
  defaultView: string;
  activeBoardId: string | null;
  zenMode: boolean;
  sidebarCollapsed: boolean;
  sidebarControl: SidebarControl;
  language: AppLanguage;
}

export const DEFAULT_NEWTAB_SETTINGS: NewTabSettings = {
  enabled: true,
  layoutMode: 'dashboard',
  cardDensity: 'comfortable',
  searchEngine: 'google',
  clockFormat: '12h',
  showClock: true,
  showQuickLinks: true,
  showTodo: true,
  showSessions: true,
  showBookmarks: true,
  backgroundType: 'gradient',
  backgroundColor: '#1a1a2e',
  backgroundGradientStops: ['#0f0c29', '#302b63', '#24243e'],
  backgroundGradientAngle: 180,
  backgroundBlur: 0,
  backgroundDimming: 10,
  backgroundSaturation: 100,
  backgroundBrightness: 100,
  backgroundVignette: false,
  dailyRotation: false,
  theme: 'system',
  defaultView: 'quick-links',
  activeBoardId: null,
  zenMode: false,
  sidebarCollapsed: false,
  sidebarControl: 'expand-on-hover',
  language: 'auto',
};

export const GRADIENT_PRESETS: GradientPreset[] = [
  { id: 'midnight', name: 'Midnight', stops: ['#1a1a2e', '#16213e'], angle: 135 },
  { id: 'ocean', name: 'Ocean', stops: ['#0f2027', '#203a43', '#2c5364'], angle: 180 },
  { id: 'sunset', name: 'Sunset', stops: ['#ff6b6b', '#feca57', '#ff9ff3'], angle: 45 },
  { id: 'forest', name: 'Forest', stops: ['#134e5e', '#71b280'], angle: 135 },
  { id: 'aurora', name: 'Aurora', stops: ['#00c6ff', '#0072ff'], angle: 135 },
  { id: 'rose', name: 'Rose', stops: ['#f093fb', '#f5576c'], angle: 135 },
  { id: 'cosmic', name: 'Cosmic', stops: ['#667eea', '#764ba2'], angle: 135 },
  { id: 'peach', name: 'Peach', stops: ['#f7971e', '#ffd200'], angle: 135 },
  { id: 'teal', name: 'Teal', stops: ['#11998e', '#38ef7d'], angle: 135 },
  { id: 'slate', name: 'Slate', stops: ['#2b5876', '#4e4376'], angle: 135 },
  { id: 'fire', name: 'Fire', stops: ['#f12711', '#f5af19'], angle: 135 },
  { id: 'night', name: 'Night', stops: ['#0f0c29', '#302b63', '#24243e'], angle: 180 },
  { id: 'mint', name: 'Mint', stops: ['#00b09b', '#96c93d'], angle: 135 },
  { id: 'indigo', name: 'Indigo', stops: ['#4776e6', '#8e54e9'], angle: 135 },
  { id: 'cherry', name: 'Cherry', stops: ['#eb3349', '#f45c43'], angle: 135 },
];

export const SEARCH_ENGINE_URLS: Record<SearchEngine, string> = {
  google: 'https://www.google.com/search?q=',
  bing: 'https://www.bing.com/search?q=',
  duckduckgo: 'https://duckduckgo.com/?q=',
  brave: 'https://search.brave.com/search?q=',
  custom: '',
};

export const NEWTAB_SETTINGS_KEY = 'newtab_settings';
