import { describe, it, expect, beforeEach } from 'vitest';
import { act } from '@testing-library/react';
import { useNewTabDataStore } from '@newtab/stores/newtab-data.store';
import type { Board, BookmarkCategory, BookmarkEntry, QuickLink, TodoList, TodoItem } from '@core/types/newtab.types';

const initialState = {
  boards: [] as Board[],
  categories: [] as BookmarkCategory[],
  entries: [] as BookmarkEntry[],
  quickLinks: [] as QuickLink[],
  todoLists: [] as TodoList[],
  todoItems: [] as TodoItem[],
};

beforeEach(() => {
  act(() => { useNewTabDataStore.setState(initialState); });
});

function makeBoard(overrides: Partial<Board> = {}): Board {
  return { id: 'b1', name: 'Board', icon: '📌', categoryIds: [], createdAt: '', updatedAt: '', ...overrides };
}

function makeCategory(overrides: Partial<BookmarkCategory> = {}): BookmarkCategory {
  return { id: 'c1', boardId: 'b1', name: 'Cat', icon: '📁', color: '#fff', bookmarkIds: [], collapsed: false, createdAt: '', ...overrides };
}

function makeEntry(overrides: Partial<BookmarkEntry> = {}): BookmarkEntry {
  return { id: 'e1', categoryId: 'c1', title: 'Entry', url: 'https://x.com', favIconUrl: '', addedAt: '', isNative: false, ...overrides };
}

function makeLink(overrides: Partial<QuickLink> = {}): QuickLink {
  return { id: 'q1', title: 'Link', url: 'https://x.com', favIconUrl: '', position: 0, isAutoGenerated: false, ...overrides };
}

function makeList(overrides: Partial<TodoList> = {}): TodoList {
  return { id: 'l1', name: 'List', icon: '📋', position: 0, createdAt: '', ...overrides };
}

function makeItem(overrides: Partial<TodoItem> = {}): TodoItem {
  return { id: 'i1', listId: 'l1', text: 'Item', completed: false, priority: 'none', position: 0, createdAt: '', ...overrides };
}

describe('newtab-data.store', () => {
  it('setBoards replaces boards array', () => {
    const boards = [makeBoard()];
    act(() => { useNewTabDataStore.getState().setBoards(boards); });
    expect(useNewTabDataStore.getState().boards).toEqual(boards);
  });

  it('setBoards with empty array clears boards', () => {
    act(() => { useNewTabDataStore.getState().setBoards([makeBoard()]); });
    act(() => { useNewTabDataStore.getState().setBoards([]); });
    expect(useNewTabDataStore.getState().boards).toEqual([]);
  });

  it('setCategories replaces categories array', () => {
    const cats = [makeCategory()];
    act(() => { useNewTabDataStore.getState().setCategories(cats); });
    expect(useNewTabDataStore.getState().categories).toEqual(cats);
  });

  it('setEntries replaces entries array', () => {
    const entries = [makeEntry()];
    act(() => { useNewTabDataStore.getState().setEntries(entries); });
    expect(useNewTabDataStore.getState().entries).toEqual(entries);
  });

  it('setQuickLinks replaces quickLinks array', () => {
    const links = [makeLink()];
    act(() => { useNewTabDataStore.getState().setQuickLinks(links); });
    expect(useNewTabDataStore.getState().quickLinks).toEqual(links);
  });

  it('setTodoLists replaces todoLists array', () => {
    const lists = [makeList()];
    act(() => { useNewTabDataStore.getState().setTodoLists(lists); });
    expect(useNewTabDataStore.getState().todoLists).toEqual(lists);
  });

  it('setTodoItems replaces todoItems array', () => {
    const items = [makeItem()];
    act(() => { useNewTabDataStore.getState().setTodoItems(items); });
    expect(useNewTabDataStore.getState().todoItems).toEqual(items);
  });

  it('setters are independent — updating boards does not affect categories', () => {
    const cats = [makeCategory()];
    act(() => { useNewTabDataStore.getState().setCategories(cats); });
    act(() => { useNewTabDataStore.getState().setBoards([makeBoard()]); });
    expect(useNewTabDataStore.getState().categories).toEqual(cats);
  });
});
