import type { QuickLink } from '@core/types/newtab.types';

interface QuickLinkMapper {
  toRow(link: QuickLink, userId: string): Record<string, unknown>;
  fromRow(row: Record<string, unknown>): QuickLink;
}

export const quicklinkMapper: QuickLinkMapper = {
  toRow(link: QuickLink, userId: string): Record<string, unknown> {
    return {
      id: link.id,
      user_id: userId,
      title: link.title,
      url: link.url,
      fav_icon_url: link.favIconUrl,
      position: link.position,
      is_auto_generated: link.isAutoGenerated,
    };
  },

  fromRow(r: Record<string, unknown>): QuickLink {
    return {
      id: r.id as string,
      title: r.title as string,
      url: r.url as string,
      favIconUrl: (r.fav_icon_url ?? '') as string,
      position: (r.position ?? 0) as number,
      isAutoGenerated: (r.is_auto_generated ?? false) as boolean,
    };
  },
};
