import type { NewTabDB } from '@core/storage/newtab-storage';
import type { QuickLink } from '@core/types/newtab.types';
import { generateId } from '@core/utils/uuid';

const STORE = 'quickLinks';

export async function getQuickLinks(db: NewTabDB): Promise<QuickLink[]> {
  const links = await db.getAll<QuickLink>(STORE);
  return links.sort((a, b) => a.position - b.position);
}

export async function saveQuickLink(
  db: NewTabDB,
  link: Omit<QuickLink, 'id'>,
): Promise<QuickLink> {
  const record: QuickLink = { ...link, id: generateId() };
  await db.put(STORE, record);
  return record;
}

export async function updateQuickLink(
  db: NewTabDB,
  id: string,
  updates: Partial<Omit<QuickLink, 'id'>>,
): Promise<void> {
  const existing = await db.get<QuickLink>(STORE, id);
  if (!existing) return;
  await db.put(STORE, { ...existing, ...updates });
}

export async function deleteQuickLink(db: NewTabDB, id: string): Promise<void> {
  await db.delete(STORE, id);
}

export async function reorderQuickLinks(db: NewTabDB, orderedIds: string[]): Promise<void> {
  const all = await db.getAll<QuickLink>(STORE);
  const map = new Map(all.map((l) => [l.id, l]));
  await Promise.all(
    orderedIds.map((id, index) => {
      const link = map.get(id);
      if (link) return db.put(STORE, { ...link, position: index });
      return Promise.resolve();
    }),
  );
}

export async function syncTopSites(db: NewTabDB): Promise<QuickLink[]> {
  const topSites = await new Promise<chrome.topSites.MostVisitedURL[]>((resolve) => {
    chrome.topSites.get(resolve);
  });

  const existing = await db.getAll<QuickLink>(STORE);
  const manualLinks = existing.filter((l) => !l.isAutoGenerated);
  const autoLinks = existing.filter((l) => l.isAutoGenerated);

  const autoMap = new Map(autoLinks.map((l) => [l.url, l]));

  const upserted: QuickLink[] = topSites.slice(0, 8).map((site, index) => {
    const existing = autoMap.get(site.url);
    return {
      id: existing?.id ?? generateId(),
      title: site.title,
      url: site.url,
      favIconUrl: `chrome://favicon/size/16@1x/${encodeURIComponent(site.url)}`,
      position: manualLinks.length + index,
      isAutoGenerated: true,
    };
  });

  await Promise.all(upserted.map((link) => db.put(STORE, link)));

  const allLinks = [...manualLinks, ...upserted];
  return allLinks.sort((a, b) => a.position - b.position);
}
