import { newtabDB } from '@core/storage/newtab-storage';
import { softDeleteNewTab } from '@core/storage/newtab-soft-delete';
import { notifySyncMutation } from '@core/services/sync-trigger';
import type { QuickLink } from '@core/types/newtab.types';
import { generateId } from '@core/utils/uuid';

const db = newtabDB;

const STORE = 'quickLinks';
const BLOCKED_KEY = 'blocked_topsites';

async function getBlockedUrls(): Promise<Set<string>> {
  return new Promise((resolve) =>
    chrome.storage.local.get(BLOCKED_KEY, (r) => resolve(new Set(r[BLOCKED_KEY] ?? []))),
  );
}

async function blockUrl(url: string): Promise<void> {
  const blocked = await getBlockedUrls();
  blocked.add(url);
  return new Promise((resolve) => chrome.storage.local.set({ [BLOCKED_KEY]: [...blocked] }, resolve));
}

export async function getQuickLinks(): Promise<QuickLink[]> {
  const links = await db.getAll<QuickLink>(STORE);
  return links
    .filter((l) => !l.isAutoGenerated && !l.deletedAt)
    .sort((a, b) => a.position - b.position);
}

export async function saveQuickLink(
  link: Omit<QuickLink, 'id'>,
): Promise<QuickLink> {
  const record: QuickLink = { ...link, id: generateId() };
  await db.put(STORE, record);
  notifySyncMutation();
  return record;
}

export async function updateQuickLink(
  id: string,
  updates: Partial<Omit<QuickLink, 'id'>>,
): Promise<void> {
  const existing = await db.get<QuickLink>(STORE, id);
  if (!existing) return;
  await db.put(STORE, { ...existing, ...updates });
  notifySyncMutation();
}

export async function deleteQuickLink(id: string, autoUrl?: string): Promise<void> {
  if (autoUrl) {
    await blockUrl(autoUrl);
    // Auto-generated links are recomputed from chrome.topSites each cycle —
    // a tombstone would be meaningless. Hard-delete.
    await db.delete(STORE, id);
  } else {
    // Manual links get pushed to Supabase — soft-delete so the engine
    // propagates the tombstone on the next cycle.
    await softDeleteNewTab(STORE, id);
  }
  notifySyncMutation();
}

export async function reorderQuickLinks(orderedIds: string[]): Promise<void> {
  const all = await db.getAll<QuickLink>(STORE);
  const map = new Map(all.map((l) => [l.id, l]));
  await Promise.all(
    orderedIds.map((id, index) => {
      const link = map.get(id);
      if (link) return db.put(STORE, { ...link, position: index });
      return Promise.resolve();
    }),
  );
  notifySyncMutation();
}

export async function syncTopSites(): Promise<QuickLink[]> {
  const topSites = await new Promise<chrome.topSites.MostVisitedURL[]>((resolve) => {
    chrome.topSites.get(resolve);
  });

  const existing = await db.getAll<QuickLink>(STORE);
  const manualLinks = existing.filter((l) => !l.isAutoGenerated);
  const autoLinks = existing.filter((l) => l.isAutoGenerated);
  const blocked = await getBlockedUrls();

  const autoMap = new Map(autoLinks.map((l) => [l.url, l]));

  const upserted: QuickLink[] = topSites
    .slice(0, 8)
    .filter((site) => !blocked.has(site.url))
    .map((site, index) => {
      const existing = autoMap.get(site.url);
      return {
        id: existing?.id ?? generateId(),
        title: site.title,
        url: site.url,
        favIconUrl: '',
        position: manualLinks.length + index,
        isAutoGenerated: true,
      };
    });

  await Promise.all(upserted.map((link) => db.put(STORE, link)));

  const allLinks = [...manualLinks, ...upserted];
  return allLinks.sort((a, b) => a.position - b.position);
}
