import { newtabDB } from '@core/storage/newtab-storage';
import { softDeleteNewTab } from '@core/storage/newtab-soft-delete';
import type { QuickLink } from '@core/types/newtab.types';
import { generateId } from '@core/utils/uuid';
import { guardAction, trackAction } from '@core/services/limits/limit-guard';

const db = newtabDB;

const STORE = 'quickLinks';
const BLOCKED_KEY = 'blocked_topsites';

async function getBlockedUrls(): Promise<Set<string>> {
  return new Promise((resolve) =>
    chrome.storage.local.get(BLOCKED_KEY, (r) => resolve(new Set(r[BLOCKED_KEY] ?? []))),
  );
}

async function blockUrl(url: string): Promise<void> {
  const blocked = await getBlockedUrls();
  blocked.add(url);
  return new Promise((resolve) => chrome.storage.local.set({ [BLOCKED_KEY]: [...blocked] }, resolve));
}

export async function getQuickLinks(): Promise<QuickLink[]> {
  const links = await db.getAll<QuickLink>(STORE);
  return links
    .filter((l) => !l.isAutoGenerated && !l.deletedAt)
    .sort((a, b) => a.position - b.position);
}

export async function saveQuickLink(
  link: Omit<QuickLink, 'id'>,
): Promise<QuickLink> {
  await guardAction();
  const record: QuickLink = { ...link, id: generateId() };
  await db.put(STORE, record);
  void trackAction();
  return record;
}

export async function updateQuickLink(
  id: string,
  updates: Partial<Omit<QuickLink, 'id'>>,
): Promise<void> {
  await guardAction();
  const existing = await db.get<QuickLink>(STORE, id);
  if (!existing) return;
  await db.put(STORE, { ...existing, ...updates });
  void trackAction();
}

export async function deleteQuickLink(id: string, autoUrl?: string): Promise<void> {
  await guardAction();
  if (autoUrl) {
    await blockUrl(autoUrl);
    await db.delete(STORE, id);
  } else {
    await softDeleteNewTab(STORE, id);
  }
  void trackAction();
}

export async function reorderQuickLinks(orderedIds: string[]): Promise<void> {
  const all = await db.getAll<QuickLink>(STORE);
  const map = new Map(all.map((l) => [l.id, l]));
  await Promise.all(
    orderedIds.map((id, index) => {
      const link = map.get(id);
      if (link) return db.put(STORE, { ...link, position: index });
      return Promise.resolve();
    }),
  );
}
