import type { NewTabDB } from '@core/storage/newtab-storage';
import type { Board, BookmarkCategory, TodoList, QuickLink } from '@core/types/newtab.types';
import { generateId } from '@core/utils/uuid';

/** Returns ISO string staggered by `offsetMs` from a base time. */
function ts(base: number, offsetMs: number): string {
  return new Date(base + offsetMs).toISOString();
}

interface SeedResult {
  mainBoard: Board;
  bookmarksBoard: Board;
  todoList: TodoList;
}

/**
 * Seeds the two default boards (Main + Bookmarks) and a default TodoList.
 * Should only be called when the DB has no boards yet.
 * Pass `{ skipSampleCards: true }` when the user is authenticated — their real
 * folders will be restored from cloud sync, so the demo Private/Work cards
 * should not be created.
 */
export async function seedDefaultData(
  db: NewTabDB,
  options?: { skipSampleCards?: boolean },
): Promise<SeedResult> {
  const base = Date.now();

  // ── Main board cards ──────────────────────────────────────────────────────

  const mainBoardId = generateId();

  const privateCard: BookmarkCategory = {
    id: generateId(),
    boardId: mainBoardId,
    name: 'Private',
    icon: '📁',
    color: '#6366f1',
    bookmarkIds: [],
    collapsed: false,
    colSpan: 3,
    rowSpan: 3,
    cardType: 'bookmark',
    createdAt: ts(base, 0),
  };

  const workCard: BookmarkCategory = {
    id: generateId(),
    boardId: mainBoardId,
    name: 'Work',
    icon: '💼',
    color: '#3b82f6',
    bookmarkIds: [],
    collapsed: false,
    colSpan: 3,
    rowSpan: 3,
    cardType: 'bookmark',
    createdAt: ts(base, 1),
  };

  const mainCards = options?.skipSampleCards ? [] : [privateCard, workCard];

  const mainBoard: Board = {
    id: mainBoardId,
    name: 'Main',
    icon: '🏠',
    categoryIds: mainCards.map((c) => c.id),
    createdAt: ts(base, 0),
    updatedAt: ts(base, 0),
  };

  // ── Default TodoList (for the TodoWidget in Focus / Minimal layouts) ───────

  const todoList: TodoList = {
    id: generateId(),
    name: 'My Tasks',
    icon: '✅',
    position: 0,
    createdAt: ts(base, 0),
  };

  // ── Bookmarks board (empty — user populates via Folder Explorer) ─────────

  const bookmarksBoardId = generateId();

  const bookmarksBoard: Board = {
    id: bookmarksBoardId,
    name: 'Bookmarks',
    icon: '🔖',
    categoryIds: [],
    createdAt: ts(base, 1),
    updatedAt: ts(base, 1),
  };

  // ── Default quick links ───────────────────────────────────────────────────

  const defaultQuickLinks: QuickLink[] = [
    { id: generateId(), title: 'Google', url: 'https://www.google.com', favIconUrl: '', position: 0, isAutoGenerated: false },
    { id: generateId(), title: 'Claude', url: 'https://claude.ai', favIconUrl: '', position: 1, isAutoGenerated: false },
    { id: generateId(), title: 'Google Translate', url: 'https://translate.google.com', favIconUrl: '', position: 2, isAutoGenerated: false },
  ];

  // ── Write everything to DB in one batch ───────────────────────────────────

  // Skip creating the default list if the user already has one (e.g. pulled from cloud).
  const existingLists = await db.getAll<TodoList>('todoLists');

  await Promise.all([
    db.put('boards', mainBoard),
    db.put('boards', bookmarksBoard),
    ...(existingLists.length === 0 ? [db.put('todoLists', todoList)] : []),
    ...mainCards.map((c) => db.put('bookmarkCategories', c)),
    ...defaultQuickLinks.map((l) => db.put('quickLinks', l)),
  ]);

  return { mainBoard, bookmarksBoard, todoList };
}
