import { useRef, useCallback, useState } from 'react';
import NewTabHeader from '@newtab/components/NewTabHeader';
import TopNavTabs from '@newtab/components/TopNavTabs';
import QuickLinksRow from '@newtab/components/QuickLinksRow';
import FrequentlyVisitedPanel from '@newtab/components/FrequentlyVisitedPanel';
import TabsPanel from '@newtab/components/TabsPanel';
import ActivityPanel from '@newtab/components/ActivityPanel';
import BookmarkBoard from '@newtab/components/BookmarkBoard';
import DashboardSidebar from '@newtab/components/DashboardSidebar';
import SessionsPanel from '@newtab/components/SessionsPanel';
import AutoSavesPanel from '@newtab/components/AutoSavesPanel';
import TabGroupsPanel from '@newtab/components/TabGroupsPanel';
import ImportExportPanel from '@newtab/components/ImportExportPanel';
import AddQuickLinkModal from '@newtab/components/AddQuickLinkModal';
import { useNewTabStore } from '@newtab/stores/newtab.store';
import { newtabDB } from '@core/storage/newtab-storage';
import * as QuickLinksService from '@core/services/quicklinks.service';
import * as BookmarkService from '@core/services/bookmark.service';
import { getFaviconUrl } from '@core/utils/favicon';
import type { QuickLink } from '@core/types/newtab.types';

export default function DashboardLayout() {
  const store = useNewTabStore();
  const { settings, activeView, quickLinks, boards, categories, entries } = store;
  const searchRef = useRef<HTMLInputElement>(null);
  const [addLinkOpen, setAddLinkOpen] = useState(false);
  const [editLink, setEditLink] = useState<QuickLink | null>(null);

  const activeBoard = boards.find((b) => b.id === settings.activeBoardId) ?? boards[0] ?? null;
  const boardCategories = activeBoard
    ? categories.filter((c) => c.boardId === activeBoard.id)
    : [];

  // ── Quick Links ──────────────────────────────────────────────
  const handleAddLink = useCallback(async (data: { title: string; url: string }) => {
    const link = await QuickLinksService.saveQuickLink(newtabDB, {
      ...data,
      favIconUrl: getFaviconUrl(data.url),
      position: quickLinks.length,
      isAutoGenerated: false,
    });
    store.setQuickLinks([...quickLinks, link]);
  }, [quickLinks, store]);

  const handleDeleteLink = useCallback(async (id: string) => {
    await QuickLinksService.deleteQuickLink(newtabDB, id);
    store.setQuickLinks(quickLinks.filter((l) => l.id !== id));
  }, [quickLinks, store]);

  const handleReorderLinks = useCallback(async (reordered: QuickLink[]) => {
    store.setQuickLinks(reordered);
    await QuickLinksService.reorderQuickLinks(newtabDB, reordered.map((l) => l.id));
  }, [store]);

  // ── Bookmarks ────────────────────────────────────────────────
  const handleAddEntry = useCallback(async (categoryId: string, title: string, url: string) => {
    const entry = await BookmarkService.saveEntry(newtabDB, {
      categoryId, title, url,
      favIconUrl: getFaviconUrl(url),
      isNative: false,
    });
    store.setEntries([...entries, entry]);
  }, [entries, store]);

  const handleDeleteEntry = useCallback(async (id: string) => {
    await BookmarkService.deleteEntry(newtabDB, id);
    store.setEntries(entries.filter((e) => e.id !== id));
  }, [entries, store]);

  const handleDeleteCategory = useCallback(async (id: string) => {
    await BookmarkService.deleteCategory(newtabDB, id);
    store.setCategories(categories.filter((c) => c.id !== id));
    store.setEntries(entries.filter((e) => e.categoryId !== id));
  }, [categories, entries, store]);

  const handleToggleCollapse = useCallback(async (id: string) => {
    const cat = categories.find((c) => c.id === id);
    if (!cat) return;
    await BookmarkService.updateCategory(newtabDB, id, { collapsed: !cat.collapsed });
    store.setCategories(categories.map((c) => (c.id === id ? { ...c, collapsed: !c.collapsed } : c)));
  }, [categories, store]);

  const handleReorderEntries = useCallback(async (_categoryId: string, orderedIds: string[]) => {
    const map = new Map(orderedIds.map((id, idx) => [id, idx]));
    store.setEntries(entries.map((e) => (map.has(e.id) ? { ...e, position: map.get(e.id)! } : e)));
  }, [entries, store]);

  const handleReorderCategories = useCallback(async (reordered: typeof categories) => {
    store.setCategories(reordered);
  }, [store]);

  const handleImportNative = useCallback(async (boardId: string) => {
    await BookmarkService.importNativeBookmarks(newtabDB, boardId);
    const newCats = await BookmarkService.getCategories(newtabDB, boardId);
    store.setCategories([...categories.filter((c) => c.boardId !== boardId), ...newCats]);
  }, [categories, store]);

  const handleAddCategory = useCallback(async (boardId: string) => {
    const cat = await BookmarkService.saveCategory(newtabDB, {
      boardId, name: 'New Category', icon: '📁',
      color: '#6366f1', bookmarkIds: [], collapsed: false,
    });
    store.setCategories([...categories, cat]);
  }, [categories, store]);

  const handleNewBoard = useCallback(async () => {
    const board = await BookmarkService.saveBoard(newtabDB, {
      name: 'New Board', icon: '📋', categoryIds: [],
    });
    store.setBoards([...boards, board]);
    store.updateSettings({ activeBoardId: board.id });
  }, [boards, store]);

  const bookmarkBoardProps = activeBoard
    ? {
        board: activeBoard,
        categories: boardCategories,
        entries,
        density: settings.cardDensity,
        onAddCategory: (id: string) => { void handleAddCategory(id); },
        onDeleteCategory: (id: string) => { void handleDeleteCategory(id); },
        onToggleCollapse: (id: string) => { void handleToggleCollapse(id); },
        onAddEntry: (catId: string, title: string, url: string) => { void handleAddEntry(catId, title, url); },
        onDeleteEntry: (id: string) => { void handleDeleteEntry(id); },
        onReorderCategories: (cats: typeof categories) => { void handleReorderCategories(cats); },
        onReorderEntries: (catId: string, ids: string[]) => { void handleReorderEntries(catId, ids); },
        onImportNative: (boardId: string) => { void handleImportNative(boardId); },
      }
    : null;

  // Determine if current view is a "sessions management" view
  const isSessionView = ['sessions', 'auto-saves', 'tab-groups', 'import-export'].includes(activeView);

  return (
    <div className="relative z-10 h-screen flex flex-col overflow-hidden">
      {/* ── Fixed header ── */}
      <NewTabHeader
        ref={searchRef}
        settings={settings}
        onOpenSettings={() => store.toggleSettings()}
        onOpenWallpaper={() => store.toggleWallpaper()}
      />

      {/* ── Body: sidebar + main ── */}
      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <DashboardSidebar
          boards={boards}
          activeBoard={activeBoard}
          collapsed={settings.sidebarCollapsed}
          activeView={activeView}
          onSelectBoard={(board) => store.updateSettings({ activeBoardId: board.id })}
          onToggle={() => store.updateSettings({ sidebarCollapsed: !settings.sidebarCollapsed })}
          onNewBoard={() => { void handleNewBoard(); }}
          onViewChange={store.setActiveView}
        />

        {/* Main content */}
        <div className="flex-1 flex flex-col overflow-hidden">
          {/* Quick Links — always pinned when visible and not in session view */}
          {settings.showQuickLinks && !isSessionView && (
            <div className="px-6 pt-4 pb-2 shrink-0">
              <QuickLinksRow
                links={quickLinks}
                onAdd={() => setAddLinkOpen(true)}
                onEdit={(link) => { setEditLink(link); setAddLinkOpen(true); }}
                onDelete={(id) => { void handleDeleteLink(id); }}
                onReorder={(links) => { void handleReorderLinks(links); }}
              />
            </div>
          )}

          {/* Navigation tabs — only for non-session views */}
          {!isSessionView && (
            <div className="px-6 pb-2 shrink-0">
              <TopNavTabs activeView={activeView} onViewChange={store.setActiveView} />
            </div>
          )}

          {/* Scrollable content */}
          <div className="flex-1 overflow-y-auto px-6 pb-6">
            <div className="max-w-7xl mx-auto">

              {/* Bookmark views */}
              {activeView === 'bookmarks' && bookmarkBoardProps && (
                <div className="pt-3">
                  <BookmarkBoard {...bookmarkBoardProps} />
                </div>
              )}
              {activeView === 'bookmarks' && !activeBoard && (
                <div className="pt-16 text-center" style={{ color: 'var(--newtab-text-secondary)' }}>
                  <p className="text-lg mb-2">No boards yet</p>
                  <p className="text-sm opacity-70">
                    Click <span className="font-medium">+ New Board</span> in the sidebar to get started
                  </p>
                </div>
              )}

              {/* Browser views */}
              {activeView === 'frequent' && <FrequentlyVisitedPanel />}
              {activeView === 'tabs' && <TabsPanel />}
              {activeView === 'activity' && <ActivityPanel />}

              {/* Session management views */}
              {activeView === 'sessions' && <SessionsPanel />}
              {activeView === 'auto-saves' && <AutoSavesPanel />}
              {activeView === 'tab-groups' && <TabGroupsPanel />}
              {activeView === 'import-export' && <ImportExportPanel />}
            </div>
          </div>
        </div>
      </div>

      <AddQuickLinkModal
        isOpen={addLinkOpen}
        onClose={() => { setAddLinkOpen(false); setEditLink(null); }}
        onSave={(data) => { void handleAddLink(data); }}
        editLink={editLink}
      />
    </div>
  );
}
