import { useRef, useCallback, useState } from 'react';
import NewTabHeader from '@newtab/components/NewTabHeader';
import ClockWidget from '@newtab/components/ClockWidget';
import QuickLinksRow from '@newtab/components/QuickLinksRow';
import BookmarkBoard from '@newtab/components/BookmarkBoard';
import DashboardSidebar from '@newtab/components/DashboardSidebar';
import SessionsPanel from '@newtab/components/SessionsPanel';
import TabGroupsPanel from '@newtab/components/TabGroupsPanel';
import ImportExportPanel from '@newtab/components/ImportExportPanel';
import SubscriptionsPanel from '@newtab/components/SubscriptionsPanel';
import SettingsView from '@newtab/components/SettingsView';
import BookmarkFolderPanel from '@newtab/components/BookmarkFolderPanel';
import AddQuickLinkModal from '@newtab/components/AddQuickLinkModal';
import { useNewTabUIStore } from '@newtab/stores/newtab-ui.store';
import { useNewTabDataStore } from '@newtab/stores/newtab-data.store';
import { newtabDB } from '@core/storage/newtab-storage';
import { updateNewTabSettings } from '@core/services/newtab-settings.service';
import * as QuickLinksService from '@core/services/quicklinks.service';
import * as BookmarkService from '@core/services/bookmark.service';
import { getFaviconUrl } from '@core/utils/favicon';
import { DEFAULT_NEWTAB_SETTINGS } from '@core/types/newtab.types';
import type { QuickLink, CardType, SpanValue } from '@core/types/newtab.types';
import { getDefaultSize, clampSize } from '@core/config/widget-config';

export default function DashboardLayout() {
  const uiStore = useNewTabUIStore();
  const dataStore = useNewTabDataStore();
  const { settings, activeView } = uiStore;
  const { quickLinks, boards, categories, entries } = dataStore;
  const searchRef = useRef<HTMLInputElement>(null);
  const [addLinkOpen, setAddLinkOpen] = useState(false);
  const [editLink, setEditLink] = useState<QuickLink | null>(null);

  const activeBoard = boards.find((b) => b.id === settings.activeBoardId) ?? boards[0] ?? null;
  // Only show top-level categories (no parentCategoryId) on the widget board grid
  const boardCategories = activeBoard
    ? categories.filter((c) => c.boardId === activeBoard.id && !c.parentCategoryId)
    : [];

  // ── Quick Links ──────────────────────────────────────────────
  const handleAddLink = useCallback(async (data: { title: string; url: string }) => {
    const link = await QuickLinksService.saveQuickLink(newtabDB, {
      ...data,
      favIconUrl: getFaviconUrl(data.url),
      position: quickLinks.length,
      isAutoGenerated: false,
    });
    dataStore.setQuickLinks([...quickLinks, link]);
  }, [quickLinks]);

  const handleEditLink = useCallback(async (data: { title: string; url: string }) => {
    if (!editLink) return;
    const updated: QuickLink = { ...editLink, ...data, favIconUrl: getFaviconUrl(data.url) };
    await QuickLinksService.updateQuickLink(newtabDB, editLink.id, updated);
    dataStore.setQuickLinks(quickLinks.map((l) => l.id === editLink.id ? updated : l));
  }, [editLink, quickLinks]);

  const handleDeleteLink = useCallback(async (id: string) => {
    const link = quickLinks.find((l) => l.id === id);
    await QuickLinksService.deleteQuickLink(newtabDB, id, link?.isAutoGenerated ? link.url : undefined);
    dataStore.setQuickLinks(quickLinks.filter((l) => l.id !== id));
  }, [quickLinks]);

  const handleReorderLinks = useCallback(async (reordered: QuickLink[]) => {
    dataStore.setQuickLinks(reordered);
    await QuickLinksService.reorderQuickLinks(newtabDB, reordered.map((l) => l.id));
  }, []);

  // ── Bookmarks ────────────────────────────────────────────────
  const handleAddEntry = useCallback(async (categoryId: string, title: string, url: string) => {
    const entry = await BookmarkService.saveEntry(newtabDB, {
      categoryId, title, url,
      favIconUrl: getFaviconUrl(url),
      isNative: false,
    });
    dataStore.setEntries([...entries, entry]);
  }, [entries]);

  const handleDeleteEntry = useCallback(async (id: string) => {
    await BookmarkService.deleteEntry(newtabDB, id);
    dataStore.setEntries(entries.filter((e) => e.id !== id));
  }, [entries]);

  const handleRenameEntry = useCallback(async (id: string, title: string, url: string) => {
    await BookmarkService.updateEntry(newtabDB, id, { title, url });
    dataStore.setEntries(entries.map((e) => (e.id === id ? { ...e, title, url } : e)));
  }, [entries]);

  const handleDeleteCategory = useCallback(async (id: string) => {
    await BookmarkService.deleteCategory(newtabDB, id);
    dataStore.setCategories(categories.filter((c) => c.id !== id));
    dataStore.setEntries(entries.filter((e) => e.categoryId !== id));
  }, [categories, entries]);

  const handleToggleCollapse = useCallback(async (id: string) => {
    const cat = categories.find((c) => c.id === id);
    if (!cat) return;
    await BookmarkService.updateCategory(newtabDB, id, { collapsed: !cat.collapsed });
    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, collapsed: !c.collapsed } : c)));
  }, [categories]);

  const handleReorderEntries = useCallback(async (categoryId: string, orderedIds: string[]) => {
    // Persist order via category's bookmarkIds
    await BookmarkService.updateCategory(newtabDB, categoryId, { bookmarkIds: orderedIds });
    // Reorder the entries array in the store so the UI reflects the new order immediately
    const map = new Map(orderedIds.map((id, idx) => [id, idx]));
    const catEntries = entries.filter((e) => e.categoryId === categoryId);
    const otherEntries = entries.filter((e) => e.categoryId !== categoryId);
    const reordered = [...catEntries].sort((a, b) => (map.get(a.id) ?? 9999) - (map.get(b.id) ?? 9999));
    dataStore.setEntries([...otherEntries, ...reordered]);
  }, [entries]);

  const handleReorderCategories = useCallback(async (reordered: typeof categories) => {
    const boardId = activeBoard?.id;
    if (boardId) {
      await BookmarkService.updateBoard(newtabDB, boardId, {
        categoryIds: reordered.map((c) => c.id),
      });
    }
    dataStore.setCategories([
      ...categories.filter((c) => c.boardId !== boardId),
      ...reordered,
    ]);
  }, [activeBoard, categories]);

  const handleImportNative = useCallback(async (boardId: string) => {
    await BookmarkService.importNativeBookmarks(newtabDB, boardId);
    const newCats = await BookmarkService.getCategories(newtabDB, boardId);
    dataStore.setCategories([...categories.filter((c) => c.boardId !== boardId), ...newCats]);
  }, [categories]);

  const handleAddCategory = useCallback(async (boardId: string, cardType: CardType = 'bookmark') => {
    const defaults: Record<CardType, { name: string; icon: string; color: string }> = {
      bookmark:           { name: 'New Widget',       icon: '📁', color: '#6366f1' },
      clock:              { name: 'Clock',            icon: '🕐', color: '#0ea5e9' },
      note:               { name: 'Note',             icon: '📝', color: '#f59e0b' },
      todo:               { name: 'To-Do',            icon: '✅', color: '#22c55e' },
      subscription:       { name: 'Subscriptions',   icon: '💳', color: '#8b5cf6' },
      'tab-groups':       { name: 'Tab Groups',       icon: '🗂️', color: '#06b6d4' },
      'native-bookmarks': { name: 'Chrome Bookmarks', icon: '🔗', color: '#e05d44' },
    };
    const cat = await BookmarkService.saveCategory(newtabDB, {
      boardId, ...defaults[cardType], bookmarkIds: [], collapsed: false, ...getDefaultSize(cardType), cardType,
    });
    dataStore.setCategories([...categories, cat]);
  }, [categories]);

  const handleResizeCategory = useCallback(async (id: string, colSpan: SpanValue, rowSpan: SpanValue) => {
    const cat = categories.find((c) => c.id === id);
    if (!cat) return;
    const clamped = clampSize(cat.cardType ?? 'bookmark', colSpan, rowSpan);
    await BookmarkService.updateCategory(newtabDB, id, clamped);
    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, ...clamped } : c)));
  }, [categories]);

  const handleUpdateNote = useCallback(async (id: string, noteContent: string) => {
    await BookmarkService.updateCategory(newtabDB, id, { noteContent });
    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, noteContent } : c)));
  }, [categories]);

  const handleRefreshQuote = useCallback(async (id: string, quoteIndex: number, quoteChangedAt: string) => {
    await BookmarkService.updateCategory(newtabDB, id, { quoteIndex, quoteChangedAt });
    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, quoteIndex, quoteChangedAt } : c)));
  }, [categories]);

  const handleRenameCard = useCallback(async (id: string, name: string) => {
    await BookmarkService.updateCategory(newtabDB, id, { name });
    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, name } : c)));
  }, [categories]);

  const handleDuplicateCard = useCallback(async (id: string) => {
    const cat = categories.find((c) => c.id === id);
    if (!cat) return;
    const catEntries = entries.filter((e) => e.categoryId === id);
    const newCat = await BookmarkService.saveCategory(newtabDB, {
      boardId: cat.boardId,
      name: `${cat.name} (copy)`,
      icon: cat.icon,
      color: cat.color,
      bookmarkIds: [],
      collapsed: false,
      ...clampSize(cat.cardType ?? 'bookmark', cat.colSpan ?? 3, cat.rowSpan ?? 3),
      cardType: cat.cardType,
      noteContent: cat.noteContent,
    });
    const newEntries = await Promise.all(
      catEntries.map((e) => BookmarkService.saveEntry(newtabDB, {
        categoryId: newCat.id,
        title: e.title,
        url: e.url,
        favIconUrl: e.favIconUrl,
        isNative: false,
      })),
    );
    dataStore.setCategories([...categories, newCat]);
    dataStore.setEntries([...entries, ...newEntries]);
  }, [categories, entries]);

  const handleNewBoard = useCallback(async () => {
    const board = await BookmarkService.saveBoard(newtabDB, {
      name: 'New Board', icon: '📋', categoryIds: [],
    });
    dataStore.setBoards([...boards, board]);
    uiStore.updateSettings({ activeBoardId: board.id });
  }, [boards]);

  const handleRenameBoard = useCallback(async (id: string, name: string) => {
    if (boards[0]?.id === id) return; // Main board is permanent
    await BookmarkService.updateBoard(newtabDB, id, { name });
    dataStore.setBoards(boards.map((b) => (b.id === id ? { ...b, name } : b)));
  }, [boards]);

  const handleDeleteBoard = useCallback(async (id: string) => {
    if (boards[0]?.id === id) return; // Main board cannot be deleted
    await BookmarkService.deleteBoard(newtabDB, id);
    const nextBoards = boards.filter((b) => b.id !== id);
    dataStore.setBoards(nextBoards);
    dataStore.setCategories(categories.filter((c) => c.boardId !== id));
    dataStore.setEntries(entries.filter((e) => {
      const cat = categories.find((c) => c.id === e.categoryId);
      return cat?.boardId !== id;
    }));
    // Switch to another board if the deleted one was active
    if (settings.activeBoardId === id) {
      uiStore.updateSettings({ activeBoardId: nextBoards[0]?.id ?? null });
    }
  }, [boards, categories, entries, settings.activeBoardId]);

  const bookmarkBoardProps = activeBoard
    ? {
        board: activeBoard,
        categories: boardCategories,
        entries,
        density: settings.cardDensity,
        isMain: boards[0]?.id === activeBoard.id,
        onAddCategory: (id: string, cardType: CardType) => { void handleAddCategory(id, cardType); },
        onDeleteCategory: (id: string) => { void handleDeleteCategory(id); },
        onToggleCollapse: (id: string) => { void handleToggleCollapse(id); },
        onAddEntry: (catId: string, title: string, url: string) => { void handleAddEntry(catId, title, url); },
        onDeleteEntry: (id: string) => { void handleDeleteEntry(id); },
        onRenameEntry: (id: string, title: string, url: string) => { void handleRenameEntry(id, title, url); },
        onReorderCategories: (cats: typeof categories) => { void handleReorderCategories(cats); },
        onReorderEntries: (catId: string, ids: string[]) => { void handleReorderEntries(catId, ids); },
        onImportNative: (boardId: string) => { void handleImportNative(boardId); },
        onResize: (id: string, colSpan: SpanValue, rowSpan: SpanValue) => { void handleResizeCategory(id, colSpan, rowSpan); },
        onUpdateNote: (id: string, content: string) => { void handleUpdateNote(id, content); },
        onRefreshQuote: (id: string, idx: number, at: string) => { void handleRefreshQuote(id, idx, at); },
        onRenameCard: (id: string, name: string) => { void handleRenameCard(id, name); },
        onDuplicateCard: (id: string) => { void handleDuplicateCard(id); },
      }
    : null;

  // Determine if current view is a "management" view (hides clock/quick links)
  const isSessionView = ['sessions', 'auto-saves', 'tab-groups', 'import-export', 'subscriptions', 'settings', 'folder-explorer'].includes(activeView);

  return (
    <div className="relative z-10 h-screen flex flex-col overflow-hidden">
      {/* ── Fixed header ── */}
      <NewTabHeader
        ref={searchRef}
        settings={settings}
        onOpenSettings={() => uiStore.toggleSettings()}
        onOpenWallpaper={() => uiStore.toggleWallpaper()}
        onToggleClock={() => uiStore.updateSettings({ showClock: !settings.showClock })}
        onLanguageChange={async (lang) => {
          uiStore.updateSettings({ language: lang }); // update React state
          await updateNewTabSettings({ language: lang }); // ensure persisted before reload
          window.location.reload();
        }}
      />

      {/* ── Body: sidebar + main ── */}
      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <DashboardSidebar
          boards={boards}
          activeBoard={activeBoard}
          collapsed={settings.sidebarCollapsed}
          activeView={activeView}
          onSelectBoard={(board) => uiStore.updateSettings({ activeBoardId: board.id })}
          onToggle={() => uiStore.updateSettings({ sidebarCollapsed: !settings.sidebarCollapsed })}
          onNewBoard={() => { void handleNewBoard(); }}
          onViewChange={uiStore.setActiveView}
          onRenameBoard={(id, name) => { void handleRenameBoard(id, name); }}
          onDeleteBoard={(id) => { void handleDeleteBoard(id); }}
          sidebarControl={settings.sidebarControl ?? 'expanded'}
          onSidebarControlChange={(mode) => uiStore.updateSettings({ sidebarControl: mode })}
        />

        {/* Main content */}
        <div className="flex-1 flex flex-col overflow-hidden">
          {/* Clock — shown above quick links when enabled and not in session view */}
          {settings.showClock && !isSessionView && (
            <div className="shrink-0 pt-5 pb-1">
              <ClockWidget clockFormat={settings.clockFormat} />
            </div>
          )}

          {/* Quick Links — always pinned when visible and not in session view */}
          {settings.showQuickLinks && !isSessionView && (
            <div className="px-[6%] pt-4 pb-2 shrink-0">
              <QuickLinksRow
                links={quickLinks}
                onAdd={() => setAddLinkOpen(true)}
                onEdit={(link) => { setEditLink(link); setAddLinkOpen(true); }}
                onDelete={(id) => { void handleDeleteLink(id); }}
                onReorder={(links) => { void handleReorderLinks(links); }}
              />
            </div>
          )}

          {/* Scrollable content */}
          <div className="flex-1 overflow-y-auto px-[6%] pb-6">
            <div>

              {/* Bookmark views */}
              {activeView === 'bookmarks' && bookmarkBoardProps && (
                <div className="pt-3">
                  <BookmarkBoard {...bookmarkBoardProps} />
                </div>
              )}
              {activeView === 'bookmarks' && !activeBoard && (
                <div className="pt-16 text-center" style={{ color: 'var(--newtab-text-secondary)' }}>
                  <p className="text-lg mb-2">No boards yet</p>
                  <p className="text-sm opacity-70">
                    Click <span className="font-medium">+ New Board</span> in the sidebar to get started
                  </p>
                </div>
              )}

              {/* Bookmark folder explorer */}
              {activeView === 'folder-explorer' && (
                <div className="h-[calc(100vh-120px)]">
                  <BookmarkFolderPanel />
                </div>
              )}

              {/* Session management views */}
              {activeView === 'sessions' && <SessionsPanel />}
              {activeView === 'tab-groups' && <TabGroupsPanel />}
              {activeView === 'import-export' && <ImportExportPanel />}

              {/* Subscriptions */}
              {activeView === 'subscriptions' && <SubscriptionsPanel />}

              {/* Settings */}
              {activeView === 'settings' && (
                <SettingsView
                  settings={settings}
                  boards={boards}
                  onUpdate={(updates) => uiStore.updateSettings(updates)}
                  onClearData={async () => {
                    await newtabDB.clearAll();
                    await updateNewTabSettings(DEFAULT_NEWTAB_SETTINGS);
                    window.location.reload();
                  }}
                />
              )}
            </div>
          </div>
        </div>
      </div>

      <AddQuickLinkModal
        isOpen={addLinkOpen}
        onClose={() => { setAddLinkOpen(false); setEditLink(null); }}
        onSave={(data) => { void (editLink ? handleEditLink(data) : handleAddLink(data)); }}
        editLink={editLink}
      />
    </div>
  );
}
