import { useRef, useCallback, useState, useEffect } from 'react';
import NewTabHeader from '@newtab/components/NewTabHeader';
import ClockWidget from '@newtab/components/ClockWidget';
import QuickLinksRow from '@newtab/components/QuickLinksRow';
import BookmarkBoard from '@newtab/components/BookmarkBoard';
import DashboardSidebar from '@newtab/components/DashboardSidebar';
import SessionsPanel from '@newtab/components/SessionsPanel';
import TabGroupsPanel from '@newtab/components/TabGroupsPanel';
import ImportExportPanel from '@newtab/components/ImportExportPanel';
import SubscriptionsPanel from '@newtab/components/SubscriptionsPanel';
import PromptsPanel from '@newtab/components/PromptsPanel';
import SettingsView from '@newtab/components/SettingsView';
import BookmarkFolderPanel from '@newtab/components/BookmarkFolderPanel';
import AddQuickLinkModal from '@newtab/components/AddQuickLinkModal';
import { useNewTabUIStore } from '@newtab/stores/newtab-ui.store';
import { useNewTabDataStore } from '@newtab/stores/newtab-data.store';
import { newtabDB } from '@core/storage/newtab-storage';
import { updateNewTabSettings } from '@core/services/newtab-settings.service';
import * as QuickLinksService from '@core/services/quicklinks.service';
import * as BookmarkService from '@core/services/bookmark.service';
import { getFaviconUrl } from '@core/utils/favicon';
import { DEFAULT_NEWTAB_SETTINGS } from '@core/types/newtab.types';
import type { QuickLink, CardType, SpanValue, BookmarkCategory } from '@core/types/newtab.types';
import { getDefaultSize, clampSize } from '@core/config/widget-config';

export default function DashboardLayout() {
  const uiStore = useNewTabUIStore();
  const dataStore = useNewTabDataStore();
  const { settings, activeView } = uiStore;
  const { quickLinks, boards, categories, entries } = dataStore;
  const searchRef = useRef<HTMLInputElement>(null);
  const [addLinkOpen, setAddLinkOpen] = useState(false);
  const [editLink, setEditLink] = useState<QuickLink | null>(null);
  const [hasUnsavedLayoutChanges, setHasUnsavedLayoutChanges] = useState(false);
  const [savedFeedback, setSavedFeedback] = useState(false);
  const pendingReorders = useRef<Record<string, string[]>>({});
  const pendingResizes = useRef<Record<string, { colSpan: SpanValue; rowSpan: SpanValue }>>({});

  const activeBoard = boards.find((b) => b.id === settings.activeBoardId) ?? boards[0] ?? null;
  // Derive board widget order from board.categoryIds so that deferred reorders
  // (pendingReorders) survive the useEffect category reload on view changes.
  const boardCategories = activeBoard
    ? activeBoard.categoryIds
        .map((id) => categories.find((c) => c.id === id))
        .filter((c): c is BookmarkCategory => c !== undefined)
    : [];

  // Only bookmark-type folders that are NOT already placed as a widget on any board.
  // Dashboard widgets (created via "Create New Folder") are in board.categoryIds;
  // Folders-page folders (created via "My Folders" +) are not.
  const availableFolders = categories.filter(
    (c) => (c.cardType === 'bookmark' || !c.cardType)
  );

  // Reload ALL categories (across every board) on every activeView change and on mount.
  // This ensures Folders-page folders (which may have a different boardId than the
  // active board) are always included — the same set that BookmarkFolderPanel shows.
  useEffect(() => {
    void BookmarkService.getAllCategories().then((cats) => {
      dataStore.setCategories(cats);
    });
  }, [activeView]);

  // ── Quick Links ──────────────────────────────────────────────
  const handleAddLink = useCallback(async (data: { title: string; url: string }) => {
    const link = await QuickLinksService.saveQuickLink({
      ...data,
      favIconUrl: getFaviconUrl(data.url),
      position: quickLinks.length,
      isAutoGenerated: false,
    });
    dataStore.setQuickLinks([...quickLinks, link]);
  }, [quickLinks]);

  const handleEditLink = useCallback(async (data: { title: string; url: string }) => {
    if (!editLink) return;
    const updated: QuickLink = { ...editLink, ...data, favIconUrl: getFaviconUrl(data.url) };
    await QuickLinksService.updateQuickLink(editLink.id, updated);
    dataStore.setQuickLinks(quickLinks.map((l) => l.id === editLink.id ? updated : l));
  }, [editLink, quickLinks]);

  const handleDeleteLink = useCallback(async (id: string) => {
    const link = quickLinks.find((l) => l.id === id);
    await QuickLinksService.deleteQuickLink(id, link?.isAutoGenerated ? link.url : undefined);
    dataStore.setQuickLinks(quickLinks.filter((l) => l.id !== id));
  }, [quickLinks]);

  const handleReorderLinks = useCallback(async (reordered: QuickLink[]) => {
    dataStore.setQuickLinks(reordered);
    await QuickLinksService.reorderQuickLinks(reordered.map((l) => l.id));
  }, []);

  // ── Bookmarks ────────────────────────────────────────────────
  const handleAddEntry = useCallback(async (categoryId: string, title: string, url: string) => {
    const entry = await BookmarkService.saveEntry({
      categoryId, title, url,
      favIconUrl: getFaviconUrl(url),
      isNative: false,
    });

    dataStore.setEntries([...entries, entry]);
  }, [entries]);

  const handleDeleteEntry = useCallback(async (id: string) => {
    await BookmarkService.deleteEntry(id);

    dataStore.setEntries(entries.filter((e) => e.id !== id));
  }, [entries]);

  const handleRenameEntry = useCallback(async (id: string, title: string, url: string) => {
    await BookmarkService.updateEntry(id, { title, url });

    dataStore.setEntries(entries.map((e) => (e.id === id ? { ...e, title, url } : e)));
  }, [entries]);

  const handleDeleteCategory = useCallback(async (id: string) => {
    const cat = categories.find((c) => c.id === id);
    await BookmarkService.removeWidgetFromBoard(id);

    // Keep category + entries in the store — the folder persists in the Folders explorer
    if (cat?.boardId) {
      dataStore.setBoards(boards.map((b) =>
        b.id === cat.boardId
          ? { ...b, categoryIds: b.categoryIds.filter((cid) => cid !== id) }
          : b,
      ));
    }
    delete pendingResizes.current[id];
    if (cat?.boardId && pendingReorders.current[cat.boardId]) {
      pendingReorders.current[cat.boardId] = pendingReorders.current[cat.boardId].filter((cid) => cid !== id);
    }
    setHasUnsavedLayoutChanges(true);
  }, [categories, boards]);

  const handleToggleCollapse = useCallback(async (id: string) => {
    const cat = categories.find((c) => c.id === id);
    if (!cat) return;
    await BookmarkService.updateCategory(id, { collapsed: !cat.collapsed });
    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, collapsed: !c.collapsed } : c)));
  }, [categories]);

  const handleReorderEntries = useCallback(async (categoryId: string, orderedIds: string[]) => {
    // Persist order via category's bookmarkIds
    await BookmarkService.updateCategory(categoryId, { bookmarkIds: orderedIds });

    // Reorder the entries array in the store so the UI reflects the new order immediately
    const map = new Map(orderedIds.map((id, idx) => [id, idx]));
    const catEntries = entries.filter((e) => e.categoryId === categoryId);
    const otherEntries = entries.filter((e) => e.categoryId !== categoryId);
    const reordered = [...catEntries].sort((a, b) => (map.get(a.id) ?? 9999) - (map.get(b.id) ?? 9999));
    dataStore.setEntries([...otherEntries, ...reordered]);
  }, [entries]);

  const handleReorderCategories = useCallback((reordered: typeof categories) => {
    const boardId = activeBoard?.id;
    if (boardId) {
      pendingReorders.current[boardId] = reordered.map((c) => c.id);
      // Update boards state so boardCategories order survives the useEffect category reload
      dataStore.setBoards(boards.map((b) =>
        b.id === boardId ? { ...b, categoryIds: reordered.map((c) => c.id) } : b,
      ));
    }
    dataStore.setCategories([
      ...categories.filter((c) => c.boardId !== boardId),
      ...reordered,
    ]);
    setHasUnsavedLayoutChanges(true);
  }, [activeBoard, categories, boards]);

  const handleImportNative = useCallback(async (boardId: string) => {
    await BookmarkService.importNativeBookmarks(boardId);

    const newCats = await BookmarkService.getCategories(boardId);
    dataStore.setCategories([...categories.filter((c) => c.boardId !== boardId), ...newCats]);
  }, [categories]);

  const handleAddCategory = useCallback(async (boardId: string, cardType: CardType = 'bookmark') => {
    const defaults: Record<CardType, { name: string; icon: string; color: string }> = {
      bookmark:           { name: 'New Widget',       icon: '📁', color: '#6366f1' },
      clock:              { name: 'Clock',            icon: '🕐', color: '#0ea5e9' },
      note:               { name: 'Note',             icon: '📝', color: '#f59e0b' },
      todo:               { name: 'To-Do',            icon: '✅', color: '#22c55e' },
      subscription:       { name: 'Subscriptions',   icon: '💳', color: '#8b5cf6' },
      'tab-groups':       { name: 'Tab Groups',       icon: '🗂️', color: '#06b6d4' },
      'native-bookmarks': { name: 'Chrome Bookmarks', icon: '🔗', color: '#e05d44' },
      weather:            { name: 'Weather',          icon: '🌤️', color: '#38bdf8' },
      downloads:          { name: 'Recent Downloads', icon: '⬇️', color: '#6366f1' },
      'prompt-manager':   { name: 'Prompts',           icon: '✨', color: '#f59e0b' },
    };
    const cat = await BookmarkService.saveCategory({
      boardId, ...defaults[cardType], bookmarkIds: [], collapsed: false, ...getDefaultSize(cardType), cardType,
    });

    dataStore.setCategories([...categories, cat]);
    // Update boards state so the new widget passes the boardCategories filter immediately
    dataStore.setBoards(boards.map((b) =>
      b.id === boardId ? { ...b, categoryIds: [...b.categoryIds, cat.id] } : b,
    ));
    setHasUnsavedLayoutChanges(true);
  }, [categories, boards]);

  const handleLinkFolder = useCallback(async (categoryId: string) => {
    if (!activeBoard) return;
    await BookmarkService.addExistingFolderAsWidget(categoryId, activeBoard.id);

    // Update boards store: add to the active board's categoryIds
    dataStore.setBoards(boards.map((b) =>
      b.id === activeBoard.id
        ? { ...b, categoryIds: [...b.categoryIds, categoryId] }
        : b,
    ));
    // If the folder was re-assigned to this board, sync its boardId in the store
    dataStore.setCategories(categories.map((c) =>
      c.id === categoryId ? { ...c, boardId: activeBoard.id } : c,
    ));
    setHasUnsavedLayoutChanges(true);
  }, [activeBoard, boards, categories]);

  const handleResizeCategory = useCallback((id: string, colSpan: SpanValue, rowSpan: SpanValue) => {
    const cat = categories.find((c) => c.id === id);
    if (!cat) return;
    const clamped = clampSize(cat.cardType ?? 'bookmark', colSpan, rowSpan);
    pendingResizes.current[id] = clamped;
    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, ...clamped } : c)));
    setHasUnsavedLayoutChanges(true);
  }, [categories]);

  const handleUpdateNote = useCallback(async (id: string, noteContent: string) => {
    await BookmarkService.updateCategory(id, { noteContent });

    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, noteContent } : c)));
  }, [categories]);

  const handleRefreshQuote = useCallback(async (id: string, quoteIndex: number, quoteChangedAt: string) => {
    await BookmarkService.updateCategory(id, { quoteIndex, quoteChangedAt });
    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, quoteIndex, quoteChangedAt } : c)));
  }, [categories]);

  const handleRenameCard = useCallback(async (id: string, name: string) => {
    await BookmarkService.updateCategory(id, { name });

    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, name } : c)));
  }, [categories]);

  const handleDuplicateCard = useCallback(async (id: string) => {
    const cat = categories.find((c) => c.id === id);
    if (!cat) return;
    const catEntries = entries.filter((e) => e.categoryId === id);
    const newCat = await BookmarkService.saveCategory({
      boardId: cat.boardId,
      name: `${cat.name} (copy)`,
      icon: cat.icon,
      color: cat.color,
      bookmarkIds: [],
      collapsed: false,
      ...clampSize(cat.cardType ?? 'bookmark', cat.colSpan ?? 3, cat.rowSpan ?? 3),
      cardType: cat.cardType,
      noteContent: cat.noteContent,
    });
    const newEntries = await Promise.all(
      catEntries.map((e) => BookmarkService.saveEntry({
        categoryId: newCat.id,
        title: e.title,
        url: e.url,
        favIconUrl: e.favIconUrl,
        isNative: false,
      })),
    );

    dataStore.setCategories([...categories, newCat]);
    dataStore.setEntries([...entries, ...newEntries]);
    // Update boards state so the duplicate passes the boardCategories filter immediately
    dataStore.setBoards(boards.map((b) =>
      b.id === newCat.boardId ? { ...b, categoryIds: [...b.categoryIds, newCat.id] } : b,
    ));
    setHasUnsavedLayoutChanges(true);
  }, [categories, entries, boards]);

  const handleSaveLayout = useCallback(async () => {
    for (const [boardId, categoryIds] of Object.entries(pendingReorders.current)) {
      await BookmarkService.updateBoard(boardId, { categoryIds });
    }
    for (const [id, size] of Object.entries(pendingResizes.current)) {
      await BookmarkService.updateCategory(id, size);
    }
    pendingReorders.current = {};
    pendingResizes.current = {};

    setHasUnsavedLayoutChanges(false);
    setSavedFeedback(true);
    setTimeout(() => setSavedFeedback(false), 2000);
  }, []);

  const handleNewBoard = useCallback(async () => {
    const board = await BookmarkService.saveBoard({
      name: 'New Board', icon: '📋', categoryIds: [],
    });

    dataStore.setBoards([...boards, board]);
    uiStore.updateSettings({ activeBoardId: board.id });
  }, [boards]);

  const handleRenameBoard = useCallback(async (id: string, name: string) => {
    if (boards[0]?.id === id) return; // Main board is permanent
    await BookmarkService.updateBoard(id, { name });

    dataStore.setBoards(boards.map((b) => (b.id === id ? { ...b, name } : b)));
  }, [boards]);

  const handleDeleteBoard = useCallback(async (id: string) => {
    if (boards[0]?.id === id) return; // Main board cannot be deleted
    await BookmarkService.deleteBoard(id);

    const nextBoards = boards.filter((b) => b.id !== id);
    dataStore.setBoards(nextBoards);
    dataStore.setCategories(categories.filter((c) => c.boardId !== id));
    dataStore.setEntries(entries.filter((e) => {
      const cat = categories.find((c) => c.id === e.categoryId);
      return cat?.boardId !== id;
    }));
    // Switch to another board if the deleted one was active
    if (settings.activeBoardId === id) {
      uiStore.updateSettings({ activeBoardId: nextBoards[0]?.id ?? null });
    }
  }, [boards, categories, entries, settings.activeBoardId]);

  const bookmarkBoardProps = activeBoard
    ? {
        board: activeBoard,
        categories: boardCategories,
        allCategories: categories,
        entries,
        density: settings.cardDensity,
        isMain: boards[0]?.id === activeBoard.id,
        availableFolders,
        onAddCategory: (id: string, cardType: CardType) => { void handleAddCategory(id, cardType); },
        onLinkFolder: (categoryId: string) => { void handleLinkFolder(categoryId); },
        onDeleteCategory: (id: string) => { void handleDeleteCategory(id); },
        onToggleCollapse: (id: string) => { void handleToggleCollapse(id); },
        onAddEntry: (catId: string, title: string, url: string) => { void handleAddEntry(catId, title, url); },
        onDeleteEntry: (id: string) => { void handleDeleteEntry(id); },
        onRenameEntry: (id: string, title: string, url: string) => { void handleRenameEntry(id, title, url); },
        onReorderCategories: (cats: typeof categories) => { void handleReorderCategories(cats); },
        onReorderEntries: (catId: string, ids: string[]) => { void handleReorderEntries(catId, ids); },
        onImportNative: (boardId: string) => { void handleImportNative(boardId); },
        onResize: (id: string, colSpan: SpanValue, rowSpan: SpanValue) => { void handleResizeCategory(id, colSpan, rowSpan); },
        onUpdateNote: (id: string, content: string) => { void handleUpdateNote(id, content); },
        onRefreshQuote: (id: string, idx: number, at: string) => { void handleRefreshQuote(id, idx, at); },
        onRenameCard: (id: string, name: string) => { void handleRenameCard(id, name); },
        onDuplicateCard: (id: string) => { void handleDuplicateCard(id); },
        hasUnsavedLayoutChanges,
        savedFeedback,
        onSaveLayout: () => { void handleSaveLayout(); },
      }
    : null;

  // Determine if current view is a "management" view (hides clock/quick links)
  const isSessionView = ['sessions', 'auto-saves', 'tab-groups', 'import-export', 'subscriptions', 'settings', 'folder-explorer', 'prompts'].includes(activeView);

  return (
    <div className="relative z-10 h-screen flex flex-col overflow-hidden">
      {/* ── Fixed header ── */}
      <NewTabHeader
        ref={searchRef}
        settings={settings}
        onOpenSettings={() => uiStore.toggleSettings()}
        onOpenWallpaper={() => uiStore.toggleWallpaper()}
        onLanguageChange={async (lang) => {
          uiStore.updateSettings({ language: lang }); // update React state
          await updateNewTabSettings({ language: lang }); // ensure persisted before reload
          window.location.reload();
        }}
      />

      {/* ── Body: sidebar + main ── */}
      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <DashboardSidebar
          boards={boards}
          activeBoard={activeBoard}
          collapsed={settings.sidebarCollapsed}
          activeView={activeView}
          onSelectBoard={(board) => uiStore.updateSettings({ activeBoardId: board.id })}
          onToggle={() => uiStore.updateSettings({ sidebarCollapsed: !settings.sidebarCollapsed })}
          onNewBoard={() => { void handleNewBoard(); }}
          onViewChange={uiStore.setActiveView}
          onRenameBoard={(id, name) => { void handleRenameBoard(id, name); }}
          onDeleteBoard={(id) => { void handleDeleteBoard(id); }}
          sidebarControl={settings.sidebarControl ?? 'expanded'}
          onSidebarControlChange={(mode) => uiStore.updateSettings({ sidebarControl: mode })}
        />

        {/* Main content */}
        <div className="flex-1 flex flex-col overflow-hidden">
          {/* Clock — shown above quick links when enabled and not in session view */}
          {settings.showClock && !isSessionView && (
            <div className="shrink-0 pt-5 pb-1">
              <ClockWidget clockFormat={settings.clockFormat} />
            </div>
          )}

          {/* Quick Links — always pinned when visible and not in session view */}
          {settings.showQuickLinks && !isSessionView && (
            <div className="px-[6%] pt-4 pb-2 shrink-0">
              <QuickLinksRow
                links={quickLinks}
                onAdd={() => setAddLinkOpen(true)}
                onEdit={(link) => { setEditLink(link); setAddLinkOpen(true); }}
                onDelete={(id) => { void handleDeleteLink(id); }}
                onReorder={(links) => { void handleReorderLinks(links); }}
              />
            </div>
          )}

          {/* Scrollable content — no side padding for full-page management views */}
          {isSessionView ? (
            <div className="flex-1 overflow-hidden h-full pb-[3%] px-[1.5%]">
              {activeView === 'folder-explorer' && <BookmarkFolderPanel />}
              {activeView === 'sessions' && <SessionsPanel />}
              {activeView === 'tab-groups' && <TabGroupsPanel />}
              {activeView === 'import-export' && <ImportExportPanel />}
              {activeView === 'subscriptions' && <SubscriptionsPanel />}
              {activeView === 'prompts' && <PromptsPanel />}
              {activeView === 'settings' && (
                <SettingsView
                  settings={settings}
                  boards={boards}
                  onUpdate={(updates) => uiStore.updateSettings(updates)}
                  onClearData={async () => {
                    await newtabDB.clearAll();
                    await updateNewTabSettings(DEFAULT_NEWTAB_SETTINGS);
                    window.location.reload();
                  }}
                />
              )}
            </div>
          ) : (
            <div className="flex-1 overflow-y-auto px-[6%] pb-6">
              <div>
                {/* Bookmark views */}
                {activeView === 'bookmarks' && bookmarkBoardProps && (
                  <div className="pt-3">
                    <BookmarkBoard {...bookmarkBoardProps} />
                  </div>
                )}
                {activeView === 'bookmarks' && !activeBoard && (
                  <div className="pt-16 text-center" style={{ color: 'var(--newtab-text-secondary)' }}>
                    <p className="text-lg mb-2">No boards yet</p>
                    <p className="text-sm opacity-70">
                      Click <span className="font-medium">+ New Board</span> in the sidebar to get started
                    </p>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      <AddQuickLinkModal
        isOpen={addLinkOpen}
        onClose={() => { setAddLinkOpen(false); setEditLink(null); }}
        onSave={(data) => { void (editLink ? handleEditLink(data) : handleAddLink(data)); }}
        editLink={editLink}
      />
    </div>
  );
}
