import { useRef, useCallback } from 'react';
import { getFaviconUrl } from '@core/utils/favicon';
import { Settings } from 'lucide-react';
import SearchBar from '@newtab/components/SearchBar';
import ClockWidget from '@newtab/components/ClockWidget';
import QuickLinksRow from '@newtab/components/QuickLinksRow';
import TodoWidget from '@newtab/components/TodoWidget';
import SessionWidget from '@newtab/components/SessionWidget';
import BookmarkBoard from '@newtab/components/BookmarkBoard';
import AddQuickLinkModal from '@newtab/components/AddQuickLinkModal';
import { useNewTabUIStore } from '@newtab/stores/newtab-ui.store';
import { useNewTabDataStore } from '@newtab/stores/newtab-data.store';
import { newtabDB } from '@core/storage/newtab-storage';
import * as QuickLinksService from '@core/services/quicklinks.service';
import * as BookmarkService from '@core/services/bookmark.service';
import * as TodoService from '@core/services/todo.service';
import { useState } from 'react';
import type { QuickLink, CardType } from '@core/types/newtab.types';
import { getDefaultSize } from '@core/config/widget-config';

function triggerCloudSync(): void {
  void chrome.runtime.sendMessage({ action: 'SYNC_NOW', payload: {} });
}

export default function FocusLayout() {
  const uiStore = useNewTabUIStore();
  const dataStore = useNewTabDataStore();
  const { settings } = uiStore;
  const { quickLinks, todoLists, todoItems, boards, categories, entries } = dataStore;
  const searchRef = useRef<HTMLInputElement>(null);
  const [addLinkOpen, setAddLinkOpen] = useState(false);
  const [editLink, setEditLink] = useState<QuickLink | null>(null);

  const activeBoard = boards.find((b) => b.id === settings.activeBoardId) ?? boards[0] ?? null;
  const activeListId = todoLists[0]?.id ?? null;

  const handleAddLink = useCallback(async (data: { title: string; url: string }) => {
    const link = await QuickLinksService.saveQuickLink(newtabDB, {
      ...data,
      favIconUrl: getFaviconUrl(data.url),
      position: quickLinks.length,
      isAutoGenerated: false,
    });
    dataStore.setQuickLinks([...quickLinks, link]);
  }, [quickLinks]);

  const handleEditLink = useCallback(async (data: { title: string; url: string }) => {
    if (!editLink) return;
    const updated: QuickLink = { ...editLink, ...data, favIconUrl: getFaviconUrl(data.url) };
    await QuickLinksService.updateQuickLink(newtabDB, editLink.id, updated);
    dataStore.setQuickLinks(quickLinks.map((l) => l.id === editLink.id ? updated : l));
  }, [editLink, quickLinks]);

  const handleDeleteLink = useCallback(async (id: string) => {
    const link = quickLinks.find((l) => l.id === id);
    await QuickLinksService.deleteQuickLink(newtabDB, id, link?.isAutoGenerated ? link.url : undefined);
    dataStore.setQuickLinks(quickLinks.filter((l) => l.id !== id));
  }, [quickLinks]);

  const handleReorderLinks = useCallback(async (reordered: QuickLink[]) => {
    dataStore.setQuickLinks(reordered);
    await QuickLinksService.reorderQuickLinks(newtabDB, reordered.map((l) => l.id));
  }, []);

  const handleAddTodo = useCallback(async (listId: string, text: string) => {
    const item = await TodoService.saveTodoItem(newtabDB, {
      listId,
      text,
      completed: false,
      priority: 'none',
      position: todoItems.filter((i) => i.listId === listId).length,
    });
    triggerCloudSync();
    dataStore.setTodoItems([...todoItems, item]);
  }, [todoItems]);

  const handleToggleTodo = useCallback(async (id: string) => {
    const item = todoItems.find((i) => i.id === id);
    if (!item) return;
    const updates = item.completed
      ? { completed: false, completedAt: undefined }
      : { completed: true, completedAt: new Date().toISOString() };
    await TodoService.updateTodoItem(newtabDB, id, updates);
    triggerCloudSync();
    dataStore.setTodoItems(todoItems.map((i) => (i.id === id ? { ...i, ...updates } : i)));
  }, [todoItems]);

  const handleDeleteTodo = useCallback(async (id: string) => {
    await TodoService.deleteTodoItem(newtabDB, id);
    triggerCloudSync();
    dataStore.setTodoItems(todoItems.filter((i) => i.id !== id));
  }, [todoItems]);

  const handleReorderTodo = useCallback(async (listId: string, orderedIds: string[]) => {
    await TodoService.reorderTodoItems(newtabDB, listId, orderedIds);
    triggerCloudSync();
    const map = new Map(orderedIds.map((id, idx) => [id, idx]));
    dataStore.setTodoItems(
      todoItems.map((i) => (map.has(i.id) ? { ...i, position: map.get(i.id)! } : i)),
    );
  }, [todoItems]);

  const handleAddEntry = useCallback(async (categoryId: string, title: string, url: string) => {
    const entry = await BookmarkService.saveEntry(newtabDB, {
      categoryId,
      title,
      url,
      favIconUrl: getFaviconUrl(url),
      isNative: false,
    });
    triggerCloudSync();
    dataStore.setEntries([...entries, entry]);
  }, [entries]);

  const handleDeleteEntry = useCallback(async (id: string) => {
    await BookmarkService.deleteEntry(newtabDB, id);
    triggerCloudSync();
    dataStore.setEntries(entries.filter((e) => e.id !== id));
  }, [entries]);

  const handleRenameEntry = useCallback(async (id: string, title: string, url: string) => {
    await BookmarkService.updateEntry(newtabDB, id, { title, url });
    triggerCloudSync();
    dataStore.setEntries(entries.map((e) => (e.id === id ? { ...e, title, url } : e)));
  }, [entries]);

  const handleDeleteCategory = useCallback(async (id: string) => {
    await BookmarkService.deleteCategory(newtabDB, id);
    triggerCloudSync();
    dataStore.setCategories(categories.filter((c) => c.id !== id));
    dataStore.setEntries(entries.filter((e) => e.categoryId !== id));
  }, [categories, entries]);

  const handleToggleCollapse = useCallback(async (id: string) => {
    const cat = categories.find((c) => c.id === id);
    if (!cat) return;
    await BookmarkService.updateCategory(newtabDB, id, { collapsed: !cat.collapsed });
    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, collapsed: !c.collapsed } : c)));
  }, [categories]);

  const handleReorderEntries = useCallback(async (_categoryId: string, orderedIds: string[]) => {
    const map = new Map(orderedIds.map((id, idx) => [id, idx]));
    dataStore.setEntries(entries.map((e) => (map.has(e.id) ? { ...e, position: map.get(e.id)! } : e)));
  }, [entries]);

  const handleReorderCategories = useCallback(async (reordered: typeof categories) => {
    dataStore.setCategories(reordered);
  }, []);

  const handleUpdateNote = useCallback(async (id: string, noteContent: string) => {
    await BookmarkService.updateCategory(newtabDB, id, { noteContent });
    triggerCloudSync();
    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, noteContent } : c)));
  }, [categories]);

  const handleRefreshQuote = useCallback(async (id: string, quoteIndex: number, quoteChangedAt: string) => {
    await BookmarkService.updateCategory(newtabDB, id, { quoteIndex, quoteChangedAt });
    dataStore.setCategories(categories.map((c) => (c.id === id ? { ...c, quoteIndex, quoteChangedAt } : c)));
  }, [categories]);

  const handleImportNative = useCallback(async (boardId: string) => {
    await BookmarkService.importNativeBookmarks(newtabDB, boardId);
    const [newCats, newEntries] = await Promise.all([
      BookmarkService.getCategories(newtabDB, boardId),
      BookmarkService.getEntries(newtabDB, categories[0]?.id ?? ''),
    ]);
    dataStore.setCategories([...categories.filter((c) => c.boardId !== boardId), ...newCats]);
    dataStore.setEntries([...entries, ...newEntries]);
  }, [categories, entries]);

  const handleAddCategory = useCallback(async (boardId: string, cardType: CardType = 'bookmark') => {
    const defaults: Record<CardType, { name: string; icon: string; color: string }> = {
      bookmark:           { name: 'New Widget',       icon: '📁', color: '#6366f1' },
      clock:              { name: 'Clock',            icon: '🕐', color: '#0ea5e9' },
      note:               { name: 'Note',             icon: '📝', color: '#f59e0b' },
      todo:               { name: 'To-Do',            icon: '✅', color: '#22c55e' },
      subscription:       { name: 'Subscriptions',   icon: '💳', color: '#8b5cf6' },
      'tab-groups':       { name: 'Tab Groups',       icon: '🗂️', color: '#06b6d4' },
      'native-bookmarks': { name: 'Chrome Bookmarks', icon: '🔗', color: '#e05d44' },
      weather:            { name: 'Weather',          icon: '🌤️', color: '#38bdf8' },
      downloads:          { name: 'Recent Downloads', icon: '⬇️', color: '#6366f1' },
      'prompt-manager':   { name: 'Prompts',           icon: '✨', color: '#f59e0b' },
    };
    const cat = await BookmarkService.saveCategory(newtabDB, {
      boardId, ...defaults[cardType], bookmarkIds: [], collapsed: false, ...getDefaultSize(cardType), cardType,
    });
    dataStore.setCategories([...categories, cat]);
  }, [categories]);

  const boardCategories = activeBoard
    ? categories.filter((c) => c.boardId === activeBoard.id)
    : [];

  return (
    <div className="relative z-10 h-screen flex flex-col overflow-hidden">
      {/* Top bar */}
      <div className="flex items-center gap-4 px-8 pt-8 pb-4">
        {settings.showClock && (
          <div className="shrink-0">
            <div className="text-3xl font-light" style={{ color: 'var(--newtab-text)', textShadow: '0 2px 20px rgba(0,0,0,0.5)' }}>
              <ClockWidget clockFormat={settings.clockFormat} />
            </div>
          </div>
        )}
        <div className="flex-1">
          <SearchBar ref={searchRef} settings={settings} />
        </div>
        <button
          onClick={() => uiStore.toggleSettings()}
          className="glass p-2.5 rounded-xl hover:bg-white/20 transition-colors shrink-0"
          aria-label="Open settings"
        >
          <Settings size={18} style={{ color: 'var(--newtab-text)' }} />
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto px-8 pb-8">
        <div className="max-w-5xl mx-auto">
          <div className="flex flex-col gap-6 pt-4">
            {settings.showQuickLinks && (
              <QuickLinksRow
                links={quickLinks}
                onAdd={() => setAddLinkOpen(true)}
                onEdit={(link) => { setEditLink(link); setAddLinkOpen(true); }}
                onDelete={(id) => { void handleDeleteLink(id); }}
                onReorder={(links) => { void handleReorderLinks(links); }}
              />
            )}
            {(settings.showTodo || settings.showSessions) && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {settings.showTodo && (
                  <TodoWidget
                    lists={todoLists}
                    items={todoItems}
                    activeListId={activeListId}
                    onListChange={() => {}}
                    onAddItem={(listId, text) => { void handleAddTodo(listId, text); }}
                    onToggleItem={(id) => { void handleToggleTodo(id); }}
                    onDeleteItem={(id) => { void handleDeleteTodo(id); }}
                    onReorder={(listId, ids) => { void handleReorderTodo(listId, ids); }}
                  />
                )}
                {settings.showSessions && <SessionWidget />}
              </div>
            )}
            {activeBoard && (
              <BookmarkBoard
                board={activeBoard}
                categories={boardCategories}
                entries={entries}
                density={settings.cardDensity}
                onAddCategory={(id, cardType) => { void handleAddCategory(id, cardType); }}
                onDeleteCategory={(id) => { void handleDeleteCategory(id); }}
                onToggleCollapse={(id) => { void handleToggleCollapse(id); }}
                onAddEntry={(catId, title, url) => { void handleAddEntry(catId, title, url); }}
                onDeleteEntry={(id) => { void handleDeleteEntry(id); }}
                onRenameEntry={(id, title, url) => { void handleRenameEntry(id, title, url); }}
                onReorderCategories={(cats) => { void handleReorderCategories(cats); }}
                onReorderEntries={(catId, ids) => { void handleReorderEntries(catId, ids); }}
                onImportNative={(boardId) => { void handleImportNative(boardId); }}
                onResize={() => {}}
                onRenameCard={() => {}}
                onDuplicateCard={() => {}}
                onUpdateNote={(id, content) => { void handleUpdateNote(id, content); }}
                onRefreshQuote={(id, idx, at) => { void handleRefreshQuote(id, idx, at); }}
              />
            )}
          </div>
        </div>
      </div>

      <AddQuickLinkModal
        isOpen={addLinkOpen}
        onClose={() => { setAddLinkOpen(false); setEditLink(null); }}
        onSave={(data) => { void (editLink ? handleEditLink(data) : handleAddLink(data)); }}
        editLink={editLink}
      />
    </div>
  );
}
