export { sendEmail } from './send'
export type { EmailType } from './send'
export { buildEmailVerificationEmail } from './templates/emailVerification'
export { buildWelcomeEmail } from './templates/welcome'
export { buildPasswordResetEmail } from './templates/passwordReset'
export { buildPasswordResetConfirmationEmail } from './templates/passwordResetConfirmation'
export { buildSupportTicketEmail } from './templates/supportTicket'
export { buildFeatureSuggestionEmail } from './templates/featureSuggestion'
export { buildBillingNotificationEmail } from './templates/billingNotification'
export { buildInvoiceReceiptEmail } from './templates/invoiceReceipt'
export { buildTrialEndingEmail } from './templates/trialEnding'
