import { IDBFactory } from 'fake-indexeddb';
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';

// Dynamically typed to avoid static import of singleton
let db: import('@core/storage/newtab-storage').NewTabDB;

function minimalSettings(): Record<string, unknown> {
  return {
    enabled: true,
    layoutMode: 'dashboard',
    cardDensity: 'comfortable',
    searchEngine: 'google',
    clockFormat: '12h',
    showClock: true,
    showQuickLinks: true,
    showTodo: true,
    showSessions: true,
    showBookmarks: true,
    backgroundType: 'gradient',
    backgroundColor: '#000',
    backgroundGradientStops: [],
    backgroundGradientAngle: 180,
    backgroundBlur: 0,
    backgroundDimming: 0,
    backgroundSaturation: 100,
    backgroundBrightness: 100,
    backgroundVignette: false,
    dailyRotation: false,
    theme: 'system',
    defaultView: 'quick-links',
    activeBoardId: null,
    zenMode: false,
    sidebarCollapsed: false,
    sidebarControl: 'expand-on-hover',
    language: 'auto',
  };
}

function buildEnvelope(boards: unknown[], settingsOverrides: Record<string, unknown> = {}) {
  return {
    source: 'browser-hub-dashboard',
    version: '1.0.0',
    exportedAt: new Date().toISOString(),
    counts: {
      boards: boards.length,
      categories: 0,
      entries: 0,
      quickLinks: 0,
      todoLists: 0,
      todoItems: 0,
    },
    boards,
    categories: [],
    entries: [],
    quickLinks: [],
    todoLists: [],
    todoItems: [],
    settings: { ...minimalSettings(), ...settingsOverrides },
  };
}

beforeEach(async () => {
  vi.resetModules();
  (globalThis as Record<string, unknown>).indexedDB = new IDBFactory();

  const { NewTabDB } = await import('@core/storage/newtab-storage');
  db = new NewTabDB();

  vi.doMock('@core/storage/newtab-storage', () => ({
    NewTabDB,
    newtabDB: db,
  }));

  vi.doMock('@core/services/newtab-settings.service', () => ({
    getNewTabSettings: vi.fn().mockResolvedValue(minimalSettings()),
    updateNewTabSettings: vi.fn().mockResolvedValue(undefined),
  }));
});

afterEach(() => {
  vi.resetModules();
});

// ---------------------------------------------------------------------------
describe('exportDashboardAsJSON', () => {
  it('produces a valid JSON envelope with the correct source and version', async () => {
    const { exportDashboardAsJSON } = await import('@core/services/newtab-export.service');

    const json = await exportDashboardAsJSON();
    const parsed = JSON.parse(json) as Record<string, unknown>;

    expect(parsed['source']).toBe('browser-hub-dashboard');
    expect(parsed['version']).toBe('1.0.0');
    expect(typeof parsed['exportedAt']).toBe('string');
  });

  it('includes all data stores in the envelope', async () => {
    const { exportDashboardAsJSON } = await import('@core/services/newtab-export.service');
    await db.put('boards', { id: 'b1', name: 'Main', icon: '🏠', categoryIds: [], createdAt: '', updatedAt: '' });
    await db.put('quickLinks', { id: 'q1', title: 'Test', url: 'https://test.com', favIconUrl: '', position: 0, isAutoGenerated: false });

    const json = await exportDashboardAsJSON();
    const parsed = JSON.parse(json) as Record<string, unknown>;

    expect(Array.isArray(parsed['boards'])).toBe(true);
    expect((parsed['boards'] as unknown[]).length).toBe(1);
    expect(Array.isArray(parsed['categories'])).toBe(true);
    expect(Array.isArray(parsed['entries'])).toBe(true);
    expect(Array.isArray(parsed['quickLinks'])).toBe(true);
    expect((parsed['quickLinks'] as unknown[]).length).toBe(1);
    expect(Array.isArray(parsed['todoLists'])).toBe(true);
    expect(Array.isArray(parsed['todoItems'])).toBe(true);
    expect(typeof parsed['settings']).toBe('object');
  });

  it('includes accurate counts in the envelope', async () => {
    const { exportDashboardAsJSON } = await import('@core/services/newtab-export.service');
    await db.put('boards', { id: 'b1', name: 'A', icon: '', categoryIds: [], createdAt: '', updatedAt: '' });
    await db.put('boards', { id: 'b2', name: 'B', icon: '', categoryIds: [], createdAt: '', updatedAt: '' });
    await db.put('todoLists', { id: 'l1', name: 'Tasks', icon: '', position: 0, createdAt: '' });

    const json = await exportDashboardAsJSON();
    const { counts } = JSON.parse(json) as { counts: Record<string, number> };

    expect(counts['boards']).toBe(2);
    expect(counts['todoLists']).toBe(1);
    expect(counts['categories']).toBe(0);
  });

  it('does not include a wallpapers key in the envelope', async () => {
    const { exportDashboardAsJSON } = await import('@core/services/newtab-export.service');
    const json = await exportDashboardAsJSON();
    const parsed = JSON.parse(json) as Record<string, unknown>;

    expect(parsed).not.toHaveProperty('wallpapers');
    expect(parsed).not.toHaveProperty('wallpaperImages');
  });
});

// ---------------------------------------------------------------------------
describe('importDashboardFromJSON', () => {
  it('returns an error for malformed JSON', async () => {
    const { importDashboardFromJSON } = await import('@core/services/newtab-export.service');

    const result = await importDashboardFromJSON('not valid json {{{');
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/valid JSON/i);
  });

  it('returns an error when the file is not a dashboard export', async () => {
    const { importDashboardFromJSON } = await import('@core/services/newtab-export.service');

    const result = await importDashboardFromJSON(JSON.stringify({ sessions: [], version: '1.0.0' }));
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/browser hub dashboard export/i);
  });

  it('returns success and counts on a valid import', async () => {
    const { importDashboardFromJSON } = await import('@core/services/newtab-export.service');

    const envelope = buildEnvelope([
      { id: 'b1', name: 'Main', icon: '', categoryIds: [], createdAt: '', updatedAt: '' },
    ]);
    const result = await importDashboardFromJSON(JSON.stringify(envelope));

    expect(result.success).toBe(true);
    expect(result.counts?.boards).toBe(1);
    expect(result.counts?.categories).toBe(0);
  });

  it('replaces existing boards with imported ones', async () => {
    const { importDashboardFromJSON } = await import('@core/services/newtab-export.service');

    await db.put('boards', { id: 'old', name: 'Old Board', icon: '', categoryIds: [], createdAt: '', updatedAt: '' });

    const envelope = buildEnvelope([
      { id: 'new', name: 'New Board', icon: '', categoryIds: [], createdAt: '', updatedAt: '' },
    ]);
    await importDashboardFromJSON(JSON.stringify(envelope));

    const boards = await db.getAll<{ id: string }>('boards');
    expect(boards).toHaveLength(1);
    expect(boards[0].id).toBe('new');
  });

  it('does not clear the wallpaperImages store', async () => {
    const { importDashboardFromJSON } = await import('@core/services/newtab-export.service');

    await db.putBlob('wp1', new Blob(['image-data']));

    await importDashboardFromJSON(JSON.stringify(buildEnvelope([])));

    const blob = await db.getBlob('wp1');
    expect(blob).not.toBeNull();
  });

  it('strips backgroundImageId and resets backgroundType when it was image', async () => {
    const { importDashboardFromJSON } = await import('@core/services/newtab-export.service');
    const { updateNewTabSettings } = await import('@core/services/newtab-settings.service');

    const envelope = buildEnvelope([], { backgroundType: 'image', backgroundImageId: 'wp-123' });
    await importDashboardFromJSON(JSON.stringify(envelope));

    const [settingsArg] = vi.mocked(updateNewTabSettings).mock.calls[0] as [Record<string, unknown>];
    expect(settingsArg['backgroundType']).toBe('gradient');
    expect(settingsArg).not.toHaveProperty('backgroundImageId');
  });

  it('preserves settings when backgroundType is not image', async () => {
    const { importDashboardFromJSON } = await import('@core/services/newtab-export.service');
    const { updateNewTabSettings } = await import('@core/services/newtab-settings.service');

    const envelope = buildEnvelope([], { backgroundType: 'gradient', theme: 'dark' });
    await importDashboardFromJSON(JSON.stringify(envelope));

    const [settingsArg] = vi.mocked(updateNewTabSettings).mock.calls[0] as [Record<string, unknown>];
    expect(settingsArg['backgroundType']).toBe('gradient');
    expect(settingsArg['theme']).toBe('dark');
  });

  it('handles an empty envelope without error', async () => {
    const { importDashboardFromJSON } = await import('@core/services/newtab-export.service');

    const result = await importDashboardFromJSON(JSON.stringify(buildEnvelope([])));
    expect(result.success).toBe(true);
    expect(await db.getAll('boards')).toHaveLength(0);
  });
});
