import { describe, it, expect, beforeEach, vi } from 'vitest';
import { IDBFactory } from 'fake-indexeddb';
import { newtabDB } from '@core/storage/newtab-storage';
import {
  getQuickLinks,
  saveQuickLink,
  updateQuickLink,
  deleteQuickLink,
  reorderQuickLinks,
  syncTopSites,
} from '@core/services/quicklinks.service';

// chrome.storage.local in-memory store for blocked URLs
let chromeStore: Record<string, unknown> = {};

function setupChromeStorage() {
  chromeStore = {};
  (chrome.storage.local.get as ReturnType<typeof vi.fn>).mockImplementation(
    (key: string, cb: (r: Record<string, unknown>) => void) => {
      cb({ [key]: chromeStore[key] });
    },
  );
  (chrome.storage.local.set as ReturnType<typeof vi.fn>).mockImplementation(
    (items: Record<string, unknown>, cb?: () => void) => {
      Object.assign(chromeStore, items);
      cb?.();
    },
  );
}

function makeLink(overrides = {}) {
  return {
    title: 'Example',
    url: 'https://example.com',
    favIconUrl: '',
    position: 0,
    isAutoGenerated: false,
    ...overrides,
  };
}

beforeEach(() => {
  (globalThis as Record<string, unknown>).indexedDB = new IDBFactory();
  (newtabDB as any).dbPromise = null;
  setupChromeStorage();
  vi.clearAllMocks();
  setupChromeStorage(); // re-setup after clearAllMocks
});

// ── getQuickLinks ─────────────────────────────────────────────────────────────

describe('getQuickLinks', () => {
  it('returns empty array initially', async () => {
    expect(await getQuickLinks()).toEqual([]);
  });

  it('excludes auto-generated links from manual list', async () => {
    await saveQuickLink(makeLink({ isAutoGenerated: false, position: 0 }));
    await saveQuickLink(makeLink({ url: 'https://auto.com', isAutoGenerated: true, position: 1 }));
    const links = await getQuickLinks();
    expect(links).toHaveLength(1);
    expect(links[0].url).toBe('https://example.com');
  });

  it('returns links sorted by position', async () => {
    await saveQuickLink(makeLink({ url: 'https://b.com', position: 1 }));
    await saveQuickLink(makeLink({ url: 'https://a.com', position: 0 }));
    const links = await getQuickLinks();
    expect(links[0].url).toBe('https://a.com');
    expect(links[1].url).toBe('https://b.com');
  });
});

// ── saveQuickLink ─────────────────────────────────────────────────────────────

describe('saveQuickLink', () => {
  it('creates a quicklink with an id', async () => {
    const link = await saveQuickLink(makeLink());
    expect(link.id).toBeTruthy();
    expect(link.title).toBe('Example');
  });
});

// ── updateQuickLink ───────────────────────────────────────────────────────────

describe('updateQuickLink', () => {
  it('updates the quicklink fields', async () => {
    const link = await saveQuickLink(makeLink({ title: 'Old' }));
    await updateQuickLink(link.id, { title: 'New' });
    const links = await getQuickLinks();
    expect(links[0].title).toBe('New');
  });

  it('is a no-op for unknown id', async () => {
    await saveQuickLink(makeLink());
    await updateQuickLink('no-such-id', { title: 'X' });
    const links = await getQuickLinks();
    expect(links[0].title).toBe('Example'); // unchanged
  });
});

// ── deleteQuickLink ───────────────────────────────────────────────────────────

describe('deleteQuickLink', () => {
  it('removes the quicklink from the store', async () => {
    const link = await saveQuickLink(makeLink());
    await deleteQuickLink(link.id);
    expect(await getQuickLinks()).toHaveLength(0);
  });

  it('blocks the URL when autoUrl is provided', async () => {
    const link = await saveQuickLink(makeLink({ url: 'https://block-me.com' }));
    await deleteQuickLink(link.id, 'https://block-me.com');
    // The blocked URL should be stored in chrome.storage.local
    const blocked = chromeStore['blocked_topsites'] as string[] | undefined;
    expect(blocked).toContain('https://block-me.com');
  });
});

// ── reorderQuickLinks ─────────────────────────────────────────────────────────

describe('reorderQuickLinks', () => {
  it('updates positions based on ordered id array', async () => {
    const a = await saveQuickLink(makeLink({ url: 'https://a.com', position: 0 }));
    const b = await saveQuickLink(makeLink({ url: 'https://b.com', position: 1 }));
    const c = await saveQuickLink(makeLink({ url: 'https://c.com', position: 2 }));

    await reorderQuickLinks([c.id, a.id, b.id]);

    const links = await getQuickLinks();
    expect(links[0].url).toBe('https://c.com');
    expect(links[1].url).toBe('https://a.com');
    expect(links[2].url).toBe('https://b.com');
  });
});

// ── syncTopSites ──────────────────────────────────────────────────────────────

describe('syncTopSites', () => {
  it('returns merged list of manual and auto-generated links', async () => {
    await saveQuickLink(makeLink({ url: 'https://manual.com', position: 0, isAutoGenerated: false }));

    (chrome.topSites.get as ReturnType<typeof vi.fn>).mockImplementation(
      (cb: (sites: chrome.topSites.MostVisitedURL[]) => void) => {
        cb([
          { url: 'https://auto1.com', title: 'Auto 1' },
          { url: 'https://auto2.com', title: 'Auto 2' },
        ]);
      },
    );

    const allLinks = await syncTopSites();
    const urls = allLinks.map((l) => l.url);
    expect(urls).toContain('https://manual.com');
    expect(urls).toContain('https://auto1.com');
    expect(urls).toContain('https://auto2.com');
  });

  it('excludes blocked URLs from auto-generated links', async () => {
    chromeStore['blocked_topsites'] = ['https://blocked.com'];

    (chrome.topSites.get as ReturnType<typeof vi.fn>).mockImplementation(
      (cb: (sites: chrome.topSites.MostVisitedURL[]) => void) => {
        cb([
          { url: 'https://blocked.com', title: 'Blocked' },
          { url: 'https://allowed.com', title: 'Allowed' },
        ]);
      },
    );

    const allLinks = await syncTopSites();
    const urls = allLinks.map((l) => l.url);
    expect(urls).not.toContain('https://blocked.com');
    expect(urls).toContain('https://allowed.com');
  });

  it('limits auto-generated sites to 8', async () => {
    (chrome.topSites.get as ReturnType<typeof vi.fn>).mockImplementation(
      (cb: (sites: chrome.topSites.MostVisitedURL[]) => void) => {
        cb(
          Array.from({ length: 12 }, (_, i) => ({
            url: `https://site${i}.com`,
            title: `Site ${i}`,
          })),
        );
      },
    );

    const allLinks = await syncTopSites();
    const autoLinks = allLinks.filter((l) => l.isAutoGenerated);
    expect(autoLinks.length).toBeLessThanOrEqual(8);
  });
});
